/*
 * ringer_test.cpp — Standalone ringer hardware test
 * XIAO ESP32S3
 *
 * Tests the telephone ringer mechanism using a 20Hz alternating signal
 * with a standard North American ring cadence: 2 seconds on, 4 seconds off.
 *
 * Wiring:
 *   D1 (GPIO 2) → Ring driver Pin A
 *   D2 (GPIO 3) → Ring driver Pin B
 *
 * The 20Hz signal is generated by alternating the two pins every 25ms:
 *   Phase 1: Pin A HIGH, Pin B LOW  (25ms)
 *   Phase 2: Pin A LOW,  Pin B HIGH (25ms)
 *   → Full cycle = 50ms = 20Hz
 */

#include <Arduino.h>

// ============================================================================
// PIN DEFINITIONS
// ============================================================================
#define PIN_RING_A  D1   // GPIO 2
#define PIN_RING_B  D2   // GPIO 3

// ============================================================================
// CADENCE CONSTANTS
// ============================================================================
#define RING_HALF_PERIOD_MS   25    // 25ms per phase → 20Hz (50ms full cycle)
#define RING_ON_DURATION_MS   2000  // Ring for 2 seconds
#define RING_OFF_DURATION_MS  4000  // Silence for 4 seconds

// ============================================================================
// ringBell()
// Generates a 20Hz alternating signal on PIN_RING_A / PIN_RING_B
// for the specified duration in milliseconds.
// ============================================================================
void ringBell(uint32_t durationMs) {
  uint32_t start = millis();

  while (millis() - start < durationMs) {
    // Phase 1: A HIGH, B LOW
    digitalWrite(PIN_RING_A, HIGH);
    digitalWrite(PIN_RING_B, LOW);
    delay(RING_HALF_PERIOD_MS);

    // Phase 2: A LOW, B HIGH
    digitalWrite(PIN_RING_A, LOW);
    digitalWrite(PIN_RING_B, HIGH);
    delay(RING_HALF_PERIOD_MS);
  }

  // Always leave both pins LOW at the end of a ring burst
  digitalWrite(PIN_RING_A, LOW);
  digitalWrite(PIN_RING_B, LOW);
}

// ============================================================================
// SETUP
// ============================================================================
void setup() {
  Serial.begin(115200);
  delay(1000);

  Serial.println("\n=================================");
  Serial.println("  Ringer Test — 20Hz / NA Cadence");
  Serial.println("  D1 = Pin A,  D2 = Pin B");
  Serial.println("  Cadence: 2s ON / 4s OFF");
  Serial.println("=================================\n");

  // Configure ringer pins as outputs, both starting LOW for safety
  pinMode(PIN_RING_A, OUTPUT);
  pinMode(PIN_RING_B, OUTPUT);
  digitalWrite(PIN_RING_A, LOW);
  digitalWrite(PIN_RING_B, LOW);

  Serial.println("[Init] Ringer pins configured. Starting cadence loop...\n");
}

// ============================================================================
// MAIN LOOP — North American ring cadence: 2s ON, 4s OFF
// ============================================================================
void loop() {
  // --- RING phase (2 seconds) ---
  Serial.println("[Ringer] Ringing...");
  ringBell(RING_ON_DURATION_MS);

  // --- SILENCE phase (4 seconds) ---
  Serial.println("[Ringer] Waiting...");
  digitalWrite(PIN_RING_A, LOW);
  digitalWrite(PIN_RING_B, LOW);
  delay(RING_OFF_DURATION_MS);
}
